-- AlterTable
ALTER TABLE `Offer` ADD COLUMN `accommodationLevel` VARCHAR(191) NULL,
    ADD COLUMN `availableDates` JSON NULL,
    ADD COLUMN `averageGroupAge` INTEGER NULL,
    ADD COLUMN `bookingUrl` VARCHAR(191) NULL,
    ADD COLUMN `cancellationPolicy` VARCHAR(191) NULL,
    ADD COLUMN `city` VARCHAR(191) NULL,
    ADD COLUMN `continent` VARCHAR(191) NULL,
    ADD COLUMN `country` VARCHAR(191) NULL,
    ADD COLUMN `currency` VARCHAR(191) NULL,
    ADD COLUMN `difficulty` VARCHAR(191) NULL,
    ADD COLUMN `durationDays` INTEGER NULL,
    ADD COLUMN `featured` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `galleryImages` JSON NULL,
    ADD COLUMN `highlights` JSON NULL,
    ADD COLUMN `imageUrl` VARCHAR(191) NULL,
    ADD COLUMN `includes` JSON NULL,
    ADD COLUMN `isActive` BOOLEAN NULL DEFAULT true,
    ADD COLUMN `languages` JSON NULL,
    ADD COLUMN `lastMinuteDeal` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `maxTravelers` INTEGER NULL,
    ADD COLUMN `originalPrice` INTEGER NULL,
    ADD COLUMN `providerId` VARCHAR(191) NULL,
    ADD COLUMN `providerName` VARCHAR(191) NULL,
    ADD COLUMN `starRating` DOUBLE NULL,
    ADD COLUMN `tags` JSON NULL,
    ADD COLUMN `terms` VARCHAR(191) NULL,
    ADD COLUMN `transportType` VARCHAR(191) NULL;
